[2025-02-13T20:40:51.561+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T20:40:51.590+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: workflow_2.Task2 manual__2025-02-13T20:40:40.121374+00:00 [queued]>
[2025-02-13T20:40:51.605+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: workflow_2.Task2 manual__2025-02-13T20:40:40.121374+00:00 [queued]>
[2025-02-13T20:40:51.606+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-13T20:40:51.638+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): Task2> on 2025-02-13 20:40:40.121374+00:00
[2025-02-13T20:40:51.647+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'workflow_2', 'Task2', 'manual__2025-02-13T20:40:40.121374+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/DAG_2.py', '--cfg-path', '/tmp/tmp2dyp3rg0']
[2025-02-13T20:40:51.650+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask Task2
[2025-02-13T20:40:51.651+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1104) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-13T20:40:51.651+0000] {standard_task_runner.py:72} INFO - Started process 1114 to run task
[2025-02-13T20:40:51.731+0000] {task_command.py:467} INFO - Running <TaskInstance: workflow_2.Task2 manual__2025-02-13T20:40:40.121374+00:00 [running]> on host f6cd8c636678
[2025-02-13T20:40:51.843+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='workflow_2' AIRFLOW_CTX_TASK_ID='Task2' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T20:40:40.121374+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T20:40:40.121374+00:00'
[2025-02-13T20:40:51.844+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T20:40:51.857+0000] {logging_mixin.py:190} INFO - Today is 2025-02-13
[2025-02-13T20:40:51.858+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-13T20:40:51.873+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T20:40:51.873+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=workflow_2, task_id=Task2, run_id=manual__2025-02-13T20:40:40.121374+00:00, execution_date=20250213T204040, start_date=20250213T204051, end_date=20250213T204051
[2025-02-13T20:40:51.947+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T20:40:51.990+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-13T20:40:52.000+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
